      save_best: True
      plot_agents: True


      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./sac_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            
            seed:
                  train: 335
                  eval: 983
                  q: 123
                  explorer: 456
                  torch: 789

            n_envs: 8
            n_steps_train: 32
            n_steps: 300_000
            eval_interval: 5000
            nb_evals: 10
            buffer_size: 1e6
            batch_size: 256
            learning_starts: 10000
            tau_target: 0.05
            max_grad_norm: 0.5
            discount_factor: 1.0
            entropy_coef: 1e-7
            target_entropy: auto
            actor_type: SquashedGaussianActor
            architecture:
                  actor_hidden_size: [128, 128]
                  critic_hidden_size: [256, 256]

      # Note: Swimmer-v3 is deprecated, but Swimmer-v4 does not seem to accept an xml_file
      gym_env:
            env_name: SwimmerBBRLEnv-v0
            xml_file: swimmer5.xml

      actor_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3

      critic_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3

      entropy_coef_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3